CREATE TABLE books (
    id UUID PRIMARY KEY,
    userid UUID NOT NULL,
    ownername TEXT NOT NULL,
    email TEXT NOT NULL,
    regno TEXT NOT NULL,
    phone TEXT NOT NULL,
    createdat TIMESTAMPTZ NOT NULL DEFAULT now(),
    coursecode TEXT NOT NULL,
    coursename TEXT NOT NULL,
    slot1 TEXT,
    slot2 TEXT,
    slot3 TEXT,
    slot4 TEXT,
    slot5 TEXT,
    slot6 TEXT,
    slot7 TEXT,
    slot8 TEXT,
    slot9 TEXT,
    slot10 TEXT,
    slot11 TEXT,
    slot12 TEXT,
    slot13 TEXT,
    slot14 TEXT,
    bookname TEXT NOT NULL,
    bookauthor TEXT NOT NULL,
    bookimage TEXT
);

