CREATE TABLE IF NOT EXISTS  users (
    id UUID PRIMARY KEY,
    firstName VARCHAR(255) NOT NULL,
    lastName VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password TEXT NOT NULL,
    regno VARCHAR(50) DEFAULT '',
    phone VARCHAR(20) DEFAULT '',
    gender VARCHAR(10) DEFAULT '',
    isbanned BOOLEAN DEFAULT FALSE,
    isadmin BOOLEAN DEFAULT FALSE,
    isvitian BOOLEAN DEFAULT FALSE,
    isverified BOOLEAN DEFAULT FALSE,
    isprofiledone BOOLEAN DEFAULT FALSE,
    createdat TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
